context:
  name: morethemes
  version: "0.3.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 02be7833e47e132fa9ed46bc344550cda2f0055cac364bbcfe3c8ec81527bf9e

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - matplotlib-base >=3.6.0, <4.0

tests:
  - python:
      imports:
      - morethemes
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://josephbarbierdarnal.github.io/morethemes/
  repository: https://github.com/JosephBARBIERDARNAL/morethemes
  summary: 'More themes for matplotlib'
  description: |
    morethemes provides themes for matplotlib. More themes, better plots, one line of code.
  license: MIT
  license_file:
    - LICENSE
    - morethemes/fonts/LICENSES/

extra:
  recipe-maintainers:
    - claudiushaag
    - JosephBARBIERDARNAL
