context:
  name: morethemes
  version: "0.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 523687cfb34f9c20ab422dd65f2bfb90202c6eda192b8f9df097f740c4f48484

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - matplotlib-base >=3.6.0, <4.0
    - pyfonts >=1.0.0

tests:
  - python:
      imports:
        - morethemes
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://josephbarbierdarnal.github.io/morethemes/
  repository: https://github.com/JosephBARBIERDARNAL/morethemes
  summary: 'More themes for matplotlib'
  description: |
    morethemes provides themes for matplotlib. More themes, better plots, one line of code.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - claudiushaag
    - JosephBARBIERDARNAL
